version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: webcrawler_mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: webcrawler
      MYSQL_USER: crawler
      MYSQL_PASSWORD: crawlerpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: .
    container_name: webcrawler_backend
    environment:
      PORT: 8080
      ENVIRONMENT: production
      DATABASE_URL: crawler:crawlerpass@tcp(mysql:3306)/webcrawler?charset=utf8mb4&parseTime=True&loc=Local
      JWT_SECRET: your-super-secret-jwt-key-change-in-production-please-make-it-long-and-random
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mysql_data:
